FROM apache/hive:4.0.0

# PostgreSQL JDBC 드라이버 다운로드 및 권한 설정
USER root
ADD https://jdbc.postgresql.org/download/postgresql-42.7.3.jar /opt/hive/lib/
RUN chmod 644 /opt/hive/lib/postgresql-42.7.3.jar

# Hadoop AWS JAR 파일을 Hive lib에 링크
RUN ln -s /opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.3.6.jar /opt/hive/lib/hadoop-aws-3.3.6.jar && \
    ln -s /opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.12.367.jar /opt/hive/lib/aws-java-sdk-bundle-1.12.367.jar